#!/usr/bin/php
<?php 
	
require 'vendor/autoload.php';

use Ramsey\Uuid\Uuid;
use Faker\Factory as Faker;

$faker = Faker::create();

const ENTRY = 10;

# users

$users = [];
for($i=1; $i<=ENTRY; $i++):
    $users[] = [
        '_id' => Uuid::uuid4()->toString(),
        'id' => $i,
        'name' => $faker->name,
        'email' => $faker->email,
        'phone' => $faker->tollFreePhoneNumber,
        'address'=> $faker->address,
        'job' => $faker->jobTitle,
        'company' => $faker->company,
        'card' => $faker->creditCardType,
        'account' => $faker->creditCardNumber,
    ];
endfor;

# articles

$articles = [];
for($i=1; $i<=ENTRY; $i++):
    $articles[] = [
        '_id' => Uuid::uuid4()->toString(),
        'id' => $i,
        'title' => $faker->bs,
        'description' => $faker->text,
        'views' => $faker->numberBetween($min = 9999, $max = 99999),
        'like'=> $faker->numberBetween($min = 99, $max = 9999),
        'dislike' => $faker->numberBetween($min = 99, $max = 9999),
        'date_published' => $faker->date($format = 'd-m-Y', $max = 'now'),
    ];
endfor;

$db = [
    'users' => $users,
    'articles' => $articles
];

$edb = json_encode($db);

file_put_contents('db.json', $edb);
