#!/usr/bin/php
<?php 

require 'vendor/autoload.php';

use Ramsey\Uuid\Uuid;
use Faker\Factory as Faker;

$faker = Faker::create();

const ENTRY = 10;

# users

############## LATEST ##############

$usersLatest = [];
for($i=1; $i<=ENTRY; $i++):
    $usersLatest[] = [
        '_id' => Uuid::uuid4()->toString(),
        'id' => $i,
        'name' => $faker->name,
        'email' => $faker->email,
        'phone' => $faker->tollFreePhoneNumber,
        'address'=> $faker->address,
        'job' => $faker->jobTitle,
        'company' => $faker->company,
        'card' => $faker->creditCardType,
        'account' => $faker->creditCardNumber,
    ];
endfor;

############## EOF LATEST ##############

############## V1 ##############

$usersV1 = [];
for($i=1; $i<=ENTRY; $i++):
    $usersV1[] = [
        '_id' => Uuid::uuid4()->toString(),
        'id' => $i,
        'name' => $faker->name,
        'email' => $faker->email,
        'phone' => $faker->tollFreePhoneNumber,
        'address'=> $faker->address,
        'job' => $faker->jobTitle,
        'company' => $faker->company,
        'card' => $faker->creditCardType,
        'account' => $faker->creditCardNumber,
    ];
endfor;

############## EOF V1 ##############

############## V0 ##############

$usersV0 = [];
for($i=1; $i<=ENTRY; $i++):
    $usersV0[] = [
        '_id' => Uuid::uuid4()->toString(),
        'id' => $i,
        'name' => $faker->name,
        'email' => $faker->email,
        'phone' => $faker->tollFreePhoneNumber,
    ];
endfor;

############## EOF V0 ##############

# articles

############## LATEST ##############

$articlesLatest = [];
for($i=1; $i<=ENTRY; $i++):
    $articlesLatest[] = [
        '_id' => Uuid::uuid4()->toString(),
        'id' => $i,
        'title' => ucfirst($faker->bs),
        'description' => $faker->text,
        'views' => $faker->numberBetween($min = 9999, $max = 99999),
        'like'=> $faker->numberBetween($min = 99, $max = 9999),
        'dislike' => $faker->numberBetween($min = 99, $max = 9999),
        'date_published' => $faker->date($format = 'd-m-Y', $max = 'now'),
    ];
endfor;

############## EOF LATEST ##############

############## V1 ##############

$articlesV1 = [];
for($i=1; $i<=ENTRY; $i++):
    $articlesV1[] = [
        '_id' => Uuid::uuid4()->toString(),
        'id' => $i,
        'title' => ucfirst($faker->bs),
        'description' => $faker->text,
        'views' => $faker->numberBetween($min = 9999, $max = 99999),
        'like'=> $faker->numberBetween($min = 99, $max = 9999),
        'dislike' => $faker->numberBetween($min = 99, $max = 9999),
        'date_published' => $faker->date($format = 'd-m-Y', $max = 'now'),
    ];
endfor;

############## EOF V1 ##############

############## V0 ##############

$articlesV0 = [];
for($i=1; $i<=ENTRY; $i++):
    $articlesV0[] = [
        '_id' => Uuid::uuid4()->toString(),
        'id' => $i,
        'title' => ucfirst($faker->bs),
        'description' => $faker->text,
    ];
endfor;

############## EOF V0 ##############

# Create fake api

$db = [
    'latest.users' => $usersLatest,
    'v1.users' => $usersV1,
    'v0.users' => $usersV0,
    'latest.articles' => $articlesLatest,
    'v1.articles' => $articlesV1,
    'v0.articles' => $articlesV0
];

$dbTypicode = [
    'users' => $usersLatest,
    'articles' => $articlesLatest,
];

$tdb = json_encode($dbTypicode);
$gdb = json_encode($db);

file_put_contents('db.json', $tdb);
file_put_contents('db-vesionning.json', $gdb);
