name: Auto deploy glitch
on: 
  push:
    branches:
      - master
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v1
      env:
        SOURCE_REPO: "https://github.com/fadilxcoder/fake-api-server.git"
        SOURCE_BRANCH: "master"
        DESTINATION_REPO: ${{ secrets.GLITCH_GIT_URL }}
        DESTINATION_BRANCH: "master"
      with:
        args: $SOURCE_REPO $SOURCE_BRANCH $DESTINATION_REPO $DESTINATION_BRANCH
